### ISSUE TITLE
gluster_volume task fails when removing brick from disconnected peer

### ISSUE THREAD

**Issue by mtruneck** [gluster/gluster-ansible-collection#32]
### The scenario:
 - gluster_volume is correctly configured across an ansible group
 - one of the group's peer disconnects permanently (cluster scaled down in our case)
 - run gluster_volume ansible without the disconnected peer in the group

### Expected result
 - `gluster_volume` task automatically removes the bricks from the disconnected peer

### Real behaviour
 - it fails with `ValueError: invalid literal for int() with base 10`.

### Reason
The problem is on the line 430 in gluster_volume.py:

https://github.com/gluster/gluster-ansible-collection/blob/3b3d406f65bc24dcb35d8004aa92ab76497aa371/plugins/modules/gluster_volume.py?plain=1#L426-L431

Because it expects output from `gluster volume heal [name] info` like this:
```
Brick 10.10.1.102:/opt/volume
Status: Connected
Number of entries: 0
```
But in case the peer disconnected, the output is
```
Brick 10.10.1.102:/opt/volume
Status: Transport endpoint is not connected
Number of entries: -
```

So the condition on line 430 fails, because ' -' is not an int.

### Task used:
```
- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ brick_name }}"
    brick: "{{ brick_dir }}"
    replicas: "{{ groups[gluster_group] | length }}"
    cluster: "{{ groups[gluster_group] | map('extract', hostvars, 'ansible_all_ipv4_addresses') | map('select', 'search', '^10\\.') | map('first') | list }}"
    host: "{{ ansible_all_ipv4_addresses | select('search', '^10\\.') | first }}"
    force: yes
  run_once: true
```
